version: 0.0
os: linux

files:
  - source: /BackendApplication.jar
    destination: /home/ec2-user/apache-tomcat-9.0.73/webapps/

file_exists_behaviour: OVERWRITE

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: server_clear.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 3600
      runas: root
